name: CI Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black isort

      - name: Run Black Formatting Check
        run: black --check .

      - name: Run Flake8 Linting
        run: flake8 .

      - name: Run isort Check
        run: isort . --check-only

      - name: Run Tests with Coverage
        run: pytest --cov=app --cov-report=xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Build Docker Image (Validation Only)
        run: docker build -t backend-ci-test .
